# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        markup = pango
        interval = 5
        separator = ""

        color_good = "#000000"
        color_degraded = "#000000"
        color_bad = "#000000"
}

#order += "ipv6"
#order += "volume master"
#order += "wireless _first_"
##order += "ethernet _first_"
#order += "battery all"
#order += "disk /"
#order += "load"
#order += "memory"
#order += "tztime local"

#wireless _first_ {
#        format_up = "WIFI:%quality at %essid"
#        format_down = "WIFI:down"
#}

#ethernet _first_ {
#        format_up = "E: %ip (%speed)"
#        format_down = "E: down"
#}

#battery all {
#        format = "%status %percentage %remaining"
#}

#disk "/" {
#        format = "%avail"
#}

#load {
#        format = "%1min"
#}

#memory {
#        format = " %used | %available"
#        threshold_degraded = "1G"
#        format_degraded = "MEMORY < %available"
#}

#tztime local {
#        format = "%b %d %H:%M"
#}

#tztime local {
#        format = "%H:%M"
#}


#order += "load"
order += "cpu_temperature 0"
order += "wireless _first_"
order += "volume master"
order += "battery 0"
order += "time"

#load {
#	format = "<span background='#b08500'>    </span><span background='#4368e6'>  %5min Load  </span>"
#}

cpu_temperature 0 {
	format = "<span background='#4368e6' foreground='#ffffff'> %degrees </span><span background='#ffffff'> 󰔄 </span>"
	path = "/sys/class/hwmon/hwmon4/temp1_input"
}

wireless _first_ {
	format_up = "<span background='#ffffff'> 󰣺 </span><span background='#4368e6' foreground='#ffffff'>  %essid  </span>"
	format_down = "<span background='#ffffff'> 󰣾 </span><span background='#4368e6' foreground='#ffffff'>  Disconnected  </span>"
}

volume master {
	format = "<span background='#ffffff'>  </span><span background='#4368e6' foreground='#ffffff'> %volume </span>"
	format_muted = "<span background='#ffffff'> 󰝟 </span><span background='#4368e6' foreground='#ffffff'> Muted </span>"
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}

battery 0 {
	last_full_capacity = true
	format = "<span background='#ffffff'> %status </span><span background='#4368e6' foreground='#ffffff'>  %percentage  </span>"
	format_down = "No Battery"
	status_chr = ""
	status_bat = ""
	status_unk = ""
	status_full = ""
	path = "/sys/class/power_supply/BAT%d/uevent"
	low_threshold = 10
	integer_battery_capacity = true
}

time {
	format = "<span background='#ffffff'> 󰔠 </span><span background='#4368e6'foreground='#ffffff'> %b %d at %H:%M </span>"
}
